### ISSUE TITLE
instance_only_statuses: Federation dropdown select fails on chrome in mobile mode

### ISSUE THREAD

**Issue by JBaczuk** [masto-donte-com-br/mastodon#3]
I've been trying to debug this, but I don't understand rails enough. Here is what I'm seeing when I try to select Local-only:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/8162417/46123394-66b5f700-c1db-11e8-9b3e-fb34044a81bb.png">

It crashes when you click throwing this error:
```
federation_dropdown.js:185 Uncaught TypeError: Cannot read property 'value' of undefined
    at r.handleModalActionClick (federation_dropdown.js:185)
    at Object.<anonymous> (react-dom.production.min.js:15)
    at Object.invokeGuardedCallback (react-dom.production.min.js:16)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:16)
    at T (react-dom.production.min.js:20)
    at I (react-dom.production.min.js:22)
    at N (react-dom.production.min.js:22)
    at M (react-dom.production.min.js:21)
    at A (react-dom.production.min.js:24)
    at R (react-dom.production.min.js:24)
```

I would love to help fix this, but I'm not sure how to rebuild the application once I modify the `federation_dropdown.js` file. I tried running precompile and then `service mastodon* restart` but it didn't seem to use the new file.

**Comment by renatolond** [comment]
That should use the new file, unless it's cached in the browser though I don't think it should be the case 🤔 I'll try to take a look!

**Comment by JBaczuk** [comment]
Yeah I'm not sure, I edited this file:

`/home/mastodon/live/app/javascript/mastodon/features/compose/components/federation_dropdown.js`

Then ran `RAILS_ENV=production bundle exec rake assets:precompile` from the `live/` directory, and run `systemctl restart mastodon-*.service` and it doesn't run the new code.

I also tested on Firefox mobile and it has the same error as above.

**Comment by renatolond** [comment]
I fixed that error. Try on your side and see how it goes :)

**Comment by JBaczuk** [comment]
Yeah, it appears to be working on firefox and chrome, thanks! Man I'm sorry I couldn't fix that for you, hopefully I can get my rails development deployment working so I can be more helpful. Do you have to run precompile every time you need to test a new change? What commands do you run to redeploy?

**Comment by renatolond** [comment]
It's easier to setup your dev env locally, because it takes care of that stuff for you, but if you are deploying to your instance, you have to pull the code and do a precompile every time you change stuff in the `app/javascript` directory. If for some reason the precompile is not working, you can force one with `rails assets:clobber`, but that will remove the existing assets, so if you're serving the instance to more people they might see some messed up css/js until the precompile finishes :)
